version: '3.7'
services:

  db:
    image: mariadb
    volumes:
      - saoirse-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE: "saoirse_production"
      MYSQL_USER: "saoirse"
      MYSQL_PASSWORD: "dashword"

  saoirse-back:
    build: 
      context: ./back/
    ports:
      - '9000:8080'
    environment:
      NODE_ENV: "production"
    depends_on:
      - "db"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  saoirse-front:
    build: 
      context: ./front/
    volumes:
      - "./front/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - '9001:8080'
    depends_on:
      - "saoirse-back"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
volumes:
  saoirse-db:
